version: '3.8'

services:
  iam:
    build:
      context: ./services/iam
    container_name: iam
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sandeepsecurities
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
